/**
 * Flows: the journeys traced from the application's source
 * (analysis/interactionRecipes.ts), written into the generated suite as a class
 * a test calls - one method per journey - and proven on the live application
 * before any test is generated.
 *
 * A model writing a long click sequence stops after the first click, picks a
 * locator that matches two elements, or skips the confirmation. A flow does
 * every step, tries the locator candidates in order at runtime (qa.runFlow),
 * moves to another table row when a row's data takes a different branch, and
 * answers every data-changing request itself. Tests set up what they observe,
 * call the flow, and assert.
 *
 *   pages/education-management.flows.ts
 *     export class EducationManagementFlows {
 *       async resetEducationSubmitConfirm(opts?: FlowOptions): Promise<void>
 *       ...
 */
import fs from 'node:fs';
import path from 'node:path';
import type { Journey, LocatorCandidate } from '../analysis/interactionRecipes.js';
import { ranked } from '../analysis/interactionRecipes.js';
import { camel, pascal, slug } from '../util/ids.js';
import { SUITE_DIRS, writeIfChanged, type SuiteLayout } from './scaffold.js';
import { runSuite } from './runner.js';
import { createLogger } from '../util/logger.js';

const log = createLogger('flows');

export const flowsClassName = (featureName: string) => `${pascal(featureName)}Flows`;
export const flowsInstanceName = (featureName: string) => camel(flowsClassName(featureName));
export const flowsFileName = (featureKey: string) => `${slug(featureKey) || 'feature'}.flows.ts`;

/** A candidate as the runtime needs it: where to look, nothing else. */
function runtime(c: LocatorCandidate) {
  const { role, name, css, text, label, inDialog, row } = c;
  return Object.fromEntries(Object.entries({ role, name, css, text, label, inDialog, row }).filter(([, v]) => v !== undefined && v !== null && v !== false));
}

/** Reliable candidates first; unreliable ones only when nothing else exists. */
function usable(list: LocatorCandidate[]) {
  const order = ranked(list);
  const good = order.filter((c) => !c.caution && !(c.live && (c.live.count !== 1 || !c.live.visible) && !c.row));
  return (good.length ? good : order).map(runtime);
}

function spec(j: Journey) {
  return {
    name: j.name,
    route: j.route,
    entry: j.entry,
    steps: j.steps.map((s) => ({
      action: s.action, what: s.what, row: s.row,
      candidates: usable(s.candidates),
      fields: s.fields.map((f) => ({ what: f.what, required: f.required, date: f.date, candidates: usable(f.candidates) })),
    })),
    guards: j.guards,
  };
}

function doc(j: Journey): string {
  const lines = [
    ...j.steps.map((s, i) => `${i + 1}. ${s.what}${s.when ? ` (code branch: ${s.when})` : ''}`),
    'Leads to:',
    ...j.leadsTo.map((t) => `  ${t.method} ${t.path} - alias "${t.alias}"${t.conditions.length ? `, only if ${t.conditions.join('; ')}` : ''}`),
    ...(j.guards.length ? [`Answers itself (never the real backend): ${j.guards.map((g) => `"${g.alias}"`).join(', ')}.`] : []),
    ...(j.proven ? [j.proven.ok ? 'Proven on the live application.' : `NOT proven: ${j.proven.detail}`] : []),
  ];
  return lines.map((l) => `   * ${l.replace(/\*\//g, '* /')}`).join('\n');
}

export function renderFlowsModule(featureName: string, journeys: Journey[]): string {
  const cls = flowsClassName(featureName);
  const flows = Object.fromEntries(journeys.map((j) => [j.name, spec(j)]));
  return `/**
 * ${featureName}: user journeys traced from the application's source.
 *
 * Generated by the Autonomous AI QA Engineer and rewritten on every review -
 * do not edit. Each method performs every step of its journey (qa.runFlow):
 * locators are tried in order, a form is completed before it is submitted, and
 * every data-changing request is answered by the flow, never the real backend.
 * Observe or intercept what you want to assert BEFORE calling a flow.
 */
import type { Page } from 'playwright/test';
import type { FlowOptions, FlowSpec, Qa } from '../support/qa';

const FLOWS: Record<string, FlowSpec> = ${JSON.stringify(flows, null, 2)};

export class ${cls} {
  constructor(readonly page: Page, readonly qa: Qa) {}
${journeys.map((j) => `
  /**
${doc(j)}
   */
  async ${j.name}(opts: FlowOptions = {}): Promise<void> {
    await this.qa.runFlow(FLOWS[${JSON.stringify(j.name)}]!, opts);
  }`).join('\n')}
}
`;
}

/** Writes pages/<feature>.flows.ts; an empty journey list removes it. */
export function writeFlowsModule(layout: SuiteLayout, featureKey: string, featureName: string, journeys: Journey[]): string | null {
  const file = path.join(layout.pagesDir, flowsFileName(featureKey));
  if (!journeys.length) { fs.rmSync(file, { force: true }); return null; }
  writeIfChanged(file, renderFlowsModule(featureName, journeys));
  return `${SUITE_DIRS.pages}/${flowsFileName(featureKey)}`;
}

/* -------------------------------------------------------------------------- */
/* Proof                                                                       */
/* -------------------------------------------------------------------------- */

const PROOF_SPEC = '__flow-proof__.spec.ts';

/** Requests a journey always sends (no condition on the way): what its proof waits for. */
function certain(j: Journey) {
  return j.leadsTo.filter((t) => t.conditions.length === 0);
}

export function renderProofSpec(features: { key: string; name: string; journeys: Journey[] }[]): string {
  const imports = features.map((f) => `import { ${flowsClassName(f.name)} } from '../${SUITE_DIRS.pages}/${flowsFileName(f.key).replace(/\.ts$/, '')}';`);
  const tests = features.flatMap((f) => f.journeys.map((j) => {
    const targets = certain(j);
    const guarded = new Set(j.guards.map((g) => g.alias));
    return `test(${JSON.stringify(`flow: ${f.key}.${j.name}`)}, async ({ page, qa }) => {
${targets.filter((t) => !guarded.has(t.alias)).map((t) => `  qa.observe(${JSON.stringify(t.alias)}, ${JSON.stringify(t.method)}, ${JSON.stringify(t.path)});`).join('\n')}
  await new ${flowsClassName(f.name)}(page, qa).${j.name}();
${targets.map((t) => `  await qa.expectRequestMade(${JSON.stringify(t.alias)});`).join('\n')}
});`;
  }));
  return `import { test } from '../support/qa';
${imports.join('\n')}

// Generated: proves each traced journey runs on the live application. Removed after the proof.
// Each journey is proven on its own: one that fails does not stop the others.
${tests.join('\n\n')}
`;
}

/**
 * Runs every journey once against the live application and records on each
 * whether it completed and sent what it always sends. Nothing is written to
 * the backend: every data-changing request is answered by the flow.
 */
export async function proveJourneys(opts: {
  layout: SuiteLayout;
  runId: string;
  baseUrl: string;
  features: { key: string; name: string; journeys: Journey[] }[];
  storageState: string | null;
  credentials?: Record<string, string>;
  signal?: AbortSignal;
}): Promise<void> {
  const features = opts.features.filter((f) => f.journeys.length);
  if (!features.length) return;
  const file = path.join(opts.layout.testsDir, PROOF_SPEC);
  fs.writeFileSync(file, renderProofSpec(features), 'utf8');
  try {
    const run = await runSuite({
      layout: opts.layout, runId: `${opts.runId}-flows`, baseUrl: opts.baseUrl, specs: [`${SUITE_DIRS.tests}/${PROOF_SPEC}`],
      storageState: opts.storageState, authRequired: Boolean(opts.storageState), credentials: opts.credentials, signal: opts.signal, retries: 0,
    });
    for (const f of features) for (const j of f.journeys) {
      const r = run.results.find((x) => x.title.endsWith(`flow: ${f.key}.${j.name}`) || x.title === `flow: ${f.key}.${j.name}`);
      const detail = r ? (r.errorMessage ?? r.outcome).split('\n').slice(0, 2).join(' ').slice(0, 300) : run.executionError ?? 'the proof did not run';
      // The network or the environment failing says nothing about the journey: it stays "not yet proven".
      if (!r || (r.outcome !== 'passed' && /net::ERR_|ECONNREFUSED|ECONNRESET|ETIMEDOUT|ENOTFOUND|Target (page|closed)|browser has been closed/.test(detail))) {
        j.proven = undefined;
        log.warn(`Journey ${f.key}.${j.name}: not proven because the environment failed (${detail.slice(0, 120)}).`);
        continue;
      }
      j.proven = { ok: r.outcome === 'passed', detail: r.outcome === 'passed' ? 'completed' : detail };
      log.info(`Journey ${f.key}.${j.name}: ${j.proven.ok ? 'proven' : `not proven - ${j.proven.detail}`}`);
    }
  } finally {
    fs.rmSync(file, { force: true });
  }
}
