/**
 * Playwright project scaffolding (spec section 13).
 *
 * Generated tests live in their own Playwright project under the project's
 * workspace, not inside the user's repository - so nothing is ever overwritten
 * in the repo, and the suite can be regenerated safely.
 *
 * Layout:
 *   playwright.config.ts
 *   tests/     one <feature>.spec.ts per feature
 *   pages/     page objects
 *   fixtures/  JSON test data
 *   support/   the qa fixture: helpers, API stubbing, evidence capture
 *   utils/     data helpers
 */
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import { env } from '../config/env.js';
import { createLogger } from '../util/logger.js';

const log = createLogger('playwright:scaffold');

export interface SuiteLayout {
  root: string;
  testsDir: string;
  pagesDir: string;
  fixturesDir: string;
  supportDir: string;
  utilsDir: string;
  artifactsDir: string;
  /** Per-run output (videos, screenshots, traces) lives under here. */
  runsDir: string;
  screenshotsDir: string;
}

/** Suite-relative directory names, used in generated paths like "tests/users.spec.ts". */
export const SUITE_DIRS = { tests: 'tests', pages: 'pages', fixtures: 'fixtures', retired: 'retired' } as const;
export const SPEC_SUFFIX = '.spec.ts';

export function suiteLayout(projectId: string): SuiteLayout {
  const root = path.join(env.workspaceRoot, projectId, 'qa-suite');
  const artifactsDir = path.join(env.artifactRoot, projectId);
  return {
    root,
    testsDir: path.join(root, SUITE_DIRS.tests),
    pagesDir: path.join(root, SUITE_DIRS.pages),
    fixturesDir: path.join(root, SUITE_DIRS.fixtures),
    supportDir: path.join(root, 'support'),
    utilsDir: path.join(root, 'utils'),
    artifactsDir,
    runsDir: path.join(artifactsDir, 'runs'),
    screenshotsDir: path.join(artifactsDir, 'screenshots'),
  };
}

const PLAYWRIGHT_CONFIG = `import { defineConfig } from 'playwright/test';

/**
 * Generated by the Autonomous AI QA Engineer.
 * Paths, the base URL and recording options are injected through environment
 * variables so the same suite runs against any environment without being
 * regenerated.
 */
const browserName = (process.env.QA_BROWSER ?? 'chromium') as 'chromium' | 'firefox' | 'webkit';
const workers = Number(process.env.QA_WORKERS ?? 1);

export default defineConfig({
  testDir: './tests',
  testMatch: '**/*.spec.ts',
  outputDir: process.env.QA_OUTPUT_DIR ?? 'test-results',
  timeout: Number(process.env.QA_TEST_TIMEOUT ?? 60000),
  expect: { timeout: Number(process.env.QA_COMMAND_TIMEOUT ?? 8000) },
  retries: Number(process.env.QA_RETRIES ?? 0),
  workers: workers > 0 ? workers : undefined,
  fullyParallel: false,
  forbidOnly: true,
  reporter: [
    // One line per finished test, so a run cut short still leaves its results.
    ['./support/progress-reporter.ts'],
    ['json', { outputFile: process.env.QA_REPORT_FILE ?? 'results.json' }],
    // The report a reviewer opens from the pull request: every test with its
    // steps, video, screenshots and trace. It must sit outside outputDir.
    ['html', { outputFolder: process.env.QA_HTML_REPORT_DIR ?? 'playwright-report', open: 'never' }],
    ['line'],
  ],
  use: {
    baseURL: process.env.QA_BASE_URL ?? 'http://localhost:3000',
    // The session verified by the review before any test ran (auth/session.ts).
    storageState: process.env.QA_STORAGE_STATE || undefined,
    browserName,
    headless: process.env.QA_HEADED !== '1',
    viewport: { width: 1280, height: 800 },
    actionTimeout: Number(process.env.QA_COMMAND_TIMEOUT ?? 8000),
    navigationTimeout: 60000,
    // Every test is recorded by default: the video is the reviewer's evidence.
    video: (process.env.QA_VIDEO ?? 'on') as 'on' | 'off' | 'retain-on-failure' | 'on-first-retry',
    screenshot: (process.env.QA_SCREENSHOT ?? 'only-on-failure') as 'on' | 'off' | 'only-on-failure',
    trace: (process.env.QA_TRACE ?? 'retain-on-failure') as 'on' | 'off' | 'retain-on-failure' | 'on-first-retry',
  },
});
`;

const SUPPORT_QA = `import { test as base, expect, type Locator, type Page, type Request } from 'playwright/test';

/**
 * The qa fixture: helpers used by generated tests, plus evidence capture.
 *
 * API stubbing: by default the generated suite stubs the application's API
 * with fixtures derived from its own TypeScript types, so the UI can be
 * exercised end to end without a seeded backend. Set TEST_MOCK_API=0 to run
 * against the real backend instead; tests that depend on stubbed data then
 * skip themselves and say why.
 *
 * Credentials come from environment values injected by the runner, which reads
 * them from the encrypted project configuration. They are never written into
 * generated test files.
 */

const ERROR_SELECTORS = '[role="alert"], [aria-invalid="true"], [data-testid*="error"], .error, .invalid-feedback, .field-error';
const DENIED_SELECTORS = '[data-testid*="unauthenticated"], [data-testid*="forbidden"], [data-testid*="denied"], [data-testid*="unauthorized"], [role="alert"]';
const DENIED_TEXT = String.raw\`(sign|log) ?in to|please (sign|log) ?in|do not have permission|not authori[sz]ed|forbidden|access denied|only administrators|unauthori[sz]ed\`;
const ERROR_TEXT = String.raw\`error|failed|try again|went wrong|could not|unable to\`;
/** Always an error when visible and non-empty. */
const ERROR_FEEDBACK_SELECTORS = '[role="alert"], [data-testid*="error"], .Toastify__toast--error, .MuiAlert-standardError, .MuiAlert-filledError, .MuiAlert-outlinedError, .ant-message-error, .ant-notification-notice-error, [data-sonner-toast][data-type="error"]';
/** Toasts, snackbars and status messages: an error only when their text reads as one. */
const FEEDBACK_SELECTORS = '[role="status"], .Toastify__toast, [class*="toast" i], [class*="snackbar" i], [class*="notistack" i], .MuiAlert-root, .ant-message, .ant-notification-notice, [data-sonner-toast]';
const EMPTY_TEXT = String.raw\`\\bno \\w+( \\w+)? (yet|found|match|matches|have been|available|to show)|you have no|nothing (here|to show)|is empty\`;

export interface QaCall { method: string; url: string; body: unknown; /** Date.now() when it was sent. */ at: number }

const credential = (key: string): string => process.env[\`QA_CRED_\${key}\`] ?? '';

const normalizePath = (p: string) => p.replace(/\\/$/, '') || '/';

/** One sign-in attempt, attached to the test so the report can say whether authenticated testing really happened. */
interface AuthRecord { mode: 'real' | 'stubbed'; role: string; ok: boolean; reason?: string; fallbackFrom?: string }
async function recordAuth(record: AuthRecord): Promise<void> {
  try {
    await base.info().attach('qa-auth', { body: JSON.stringify(record), contentType: 'application/json' });
  } catch { /* outside a test: nothing to attach to */ }
}

/** A locator candidate of a flow step (analysis/interactionRecipes.ts). */
export interface FlowLocator { role?: string; name?: string; css?: string; text?: string; label?: string; inDialog?: boolean; row?: { column: string | null } | null }

/** A user journey traced from the application's source. */
export interface FlowSpec {
  name: string;
  route: string | null;
  /** Open route by following the first link to it on the via page (it needs query values only real data has). */
  entry?: { via: string; link: string } | null;
  steps: {
    action: 'click' | 'submit' | 'confirm';
    what: string;
    row: { column: string | null } | null;
    candidates: FlowLocator[];
    fields: { what: string; required: boolean; date: boolean; candidates: FlowLocator[] }[];
  }[];
  /** Data-changing requests on the way: answered by the flow under these aliases. */
  guards: { method: string; path: string; alias: string }[];
}

export interface FlowOptions {
  /** Controlled responses for the journey's guarded requests, by alias (default 200 {}). */
  respond?: Record<string, { statusCode?: number; body?: unknown }>;
  /** The table row to start with (0-based); a row whose data takes another branch is skipped. */
  row?: number;
  /** Values for form fields, by label. */
  values?: Record<string, string>;
  /** Open the journey's page first when not already on it (default true). */
  goto?: boolean;
}

export class Qa {
  readonly mockApi: boolean;
  private readonly calls = new Map<string, QaCall[]>();
  /** Requests a test or flow already answers (qa.intercept): the write guard leaves them to it. */
  private readonly intercepted: { method: string; re: RegExp }[] = [];
  private writesBlocked = false;
  /** When the last flow performed its final step: what the application did after it is what that step caused. */
  private finalStepAt = 0;

  /** Requests in flight and the time of the last request activity, for settle(). */
  private inflight = 0;
  private lastActivity = Date.now();

  constructor(private readonly page: Page) {
    const flag = process.env.QA_MOCK_API ?? '1';
    this.mockApi = flag !== '0' && flag !== 'false';
    page.on('request', () => { this.inflight++; this.lastActivity = Date.now(); });
    const done = () => { this.inflight = Math.max(0, this.inflight - 1); this.lastActivity = Date.now(); };
    page.on('requestfinished', done);
    page.on('requestfailed', done);
  }

  /**
   * Waits until no request has started or finished for quietMs (and none is in
   * flight), or maxMs passes. "networkidle" cannot do this: it fires once per
   * page load, so after it a check of what was NOT requested would run at once
   * - before a refetch that follows a save has even started.
   */
  async settle(quietMs = 1500, maxMs = 10000): Promise<void> {
    const deadline = Date.now() + maxMs;
    while (Date.now() < deadline) {
      const quiet = Date.now() - this.lastActivity;
      if (this.inflight === 0 && quiet >= quietMs) return;
      // A long-lived request (a stream, a poll) never finishes: a quiet period with nothing new is enough.
      if (quiet >= quietMs * 2) return;
      await new Promise((r) => setTimeout(r, 100));
    }
  }

  private record(alias: string, request: Request): void {
    let body: unknown = request.postData();
    try { body = request.postDataJSON(); } catch { /* not JSON */ }
    const list = this.calls.get(alias) ?? [];
    list.push({ method: request.method(), url: request.url(), body, at: Date.now() });
    this.calls.set(alias, list);
  }

  callsFor(alias: string): QaCall[] {
    return this.calls.get(alias) ?? [];
  }

  /**
   * Evaluates in the page for a polled assertion. A navigation in progress
   * destroys the execution context; that means "not yet", so the fallback is
   * returned and the poll tries again instead of failing the test.
   */
  private async probe<T, A>(fn: (arg: A) => T, arg: A, notYet: T): Promise<T> {
    try {
      return await this.page.evaluate(fn as never, arg) as T;
    } catch (e) {
      if (/Execution context was destroyed|navigat|Target closed|frame was detached/i.test(String((e as Error).message))) return notYet;
      throw e;
    }
  }

  /** Answers matching API requests with a canned response. No-op against a real backend. */
  async stub(method: string, pathPattern: string, response: { statusCode?: number; body?: unknown }, alias?: string): Promise<void> {
    if (!this.mockApi) return;
    const matcher = new RegExp(\`\${pathPattern}(\\\\?.*)?$\`);
    const wanted = method.toUpperCase();
    await this.page.route(matcher, async (route, request) => {
      if (request.method() !== wanted) return route.fallback();
      if (wanted === 'GET') {
        // A page route can share its path with an API route (/tasks is both),
        // so document loads and framework navigation requests pass through;
        // only data requests are answered.
        const headers = request.headers();
        if (request.resourceType() === 'document' || (headers['accept'] ?? '').includes('text/html') || headers['rsc']) {
          return route.fallback();
        }
      }
      if (alias) this.record(alias, request);
      await route.fulfill({
        status: response.statusCode ?? 200,
        contentType: 'application/json',
        body: JSON.stringify(response.body ?? {}),
      });
    });
  }

  /**
   * Signs in as a role. With API stubbing the session endpoint answers with the
   * given session (or 401 for null); against a real backend the configured
   * credentials are used to log in through the UI.
   */
  async session(sessionPath: string | null, session: Record<string, unknown> | null, role?: string): Promise<void> {
    // The review verified a real session before any test ran, and every test
    // starts with it. Signed in: keep it. Signed out: drop it.
    if (process.env.QA_STORAGE_STATE) {
      if (!session) {
        await this.page.context().clearCookies();
        await this.page.addInitScript(() => { try { localStorage.clear(); sessionStorage.clear(); } catch { /* opaque origin */ } });
        return;
      }
      await recordAuth({ mode: 'real', role: role ?? 'user', ok: true, reason: 'verified session' });
      return;
    }
    if (process.env.QA_AUTH_REQUIRED === '1' && session) {
      await recordAuth({ mode: 'real', role: role ?? 'user', ok: false, reason: 'no verified session' });
      throw new Error('AUTHENTICATION_REQUIRED: this module requires signing in and no verified session was provided.');
    }
    if (this.mockApi) {
      if (sessionPath) {
        await this.stub('GET', sessionPath.replace(/[.*+?^\${}()|[\\]\\\\]/g, '\\\\$&'),
          session ? { statusCode: 200, body: session } : { statusCode: 401, body: {} }, 'qaSession');
      }
      if (session) await recordAuth({ mode: 'stubbed', role: role ?? 'user', ok: true });
      return;
    }
    await this.page.context().clearCookies();
    if (session) await this.loginAs(role ?? 'user');
  }

  /**
   * Signs in through the application's own login form and proves it worked:
   * the page must leave the login route and the password field must be gone.
   * A failure is reported as AUTHENTICATION_FAILURE with what the page said,
   * so it is never mistaken for a defect in the feature under test.
   */
  async loginAs(requested: string = 'user'): Promise<void> {
    // A role without its own account falls back to the ordinary user, and the
    // report says so rather than pretending the role was exercised.
    const hasOwn = Boolean(credential(\`\${requested}Email\`) && credential(\`\${requested}Password\`));
    const role = hasOwn ? requested : 'user';
    const email = credential(\`\${role}Email\`);
    const password = credential(\`\${role}Password\`);
    if (!email || !password) {
      await recordAuth({ mode: 'real', role: requested, ok: false, reason: 'no credentials configured' });
      throw new Error(
        \`AUTHENTICATION_FAILURE: no \${role} credentials configured. Set TEST_\${role.toUpperCase()}_EMAIL and \` +
        \`TEST_\${role.toUpperCase()}_PASSWORD, or store credentials on the project.\`,
      );
    }
    const loginPath = credential('loginPath') || '/login';
    try {
      await this.page.goto(loginPath);
      await this.page.locator('input[type="email"], input[name="email"], input[name="username"], [data-testid="email"]').first().fill(email);
      await this.page.locator('input[type="password"], input[name="password"], [data-testid="password"]').first().fill(password);
      await this.page.locator('button[type="submit"], [data-testid="login-submit"]').first().click();
      await expect.poll(async () => {
        const onLogin = /log-?in|sign-?in|auth/i.test(new URL(this.page.url()).pathname);
        const passwordShown = await this.page.locator('input[type="password"]').first().isVisible().catch(() => false);
        return !onLogin && !passwordShown;
      }, { timeout: 15000, message: \`expected to be signed in as \${role}\` }).toBe(true);
    } catch (e) {
      const said = await this.page.locator('[role="alert"], [data-testid*="error"], .error, .invalid-feedback')
        .first().textContent({ timeout: 500 }).catch(() => null);
      const reason = (said?.trim() || (e as Error).message.split('\\n')[0] || 'unknown').replaceAll(password, '***').slice(0, 200);
      await recordAuth({ mode: 'real', role, ok: false, reason });
      throw new Error(\`AUTHENTICATION_FAILURE: could not sign in as \${role} at \${loginPath}: \${reason}\`);
    }
    await recordAuth({ mode: 'real', role, ok: true, ...(role !== requested ? { fallbackFrom: requested } : {}) });
  }

  /** Fills an input (or chooses a select option). A field with maxlength is typed so the cap applies. */
  async fill(selector: string, value: string): Promise<void> {
    const field = this.page.locator(selector).first();
    const tag = await field.evaluate((el) => el.tagName);
    if (tag === 'SELECT') {
      if (value) await field.selectOption(value);
      return;
    }
    await field.fill('');
    if (value === '') return;
    if (await field.getAttribute('maxlength')) await field.pressSequentially(value);
    else await field.fill(value);
  }

  /** Waits until a stubbed request with this alias has been sent, and returns it. */
  async waitFor(alias: string): Promise<QaCall> {
    await expect.poll(() => this.callsFor(alias).length, { message: \`expected the request aliased "\${alias}" to have been sent\` }).toBeGreaterThan(0);
    const calls = this.callsFor(alias);
    return calls[calls.length - 1]!;
  }

  async expectNotCalled(alias: string): Promise<void> {
    if (!this.mockApi) return;
    expect(this.callsFor(alias), \`expected no request aliased "\${alias}" to be sent\`).toHaveLength(0);
  }

  /* -- Network observation: the evidence for behaviour that has no selector -- */

  /**
   * Records every request matching method + path pattern from now on, whether
   * it is stubbed, intercepted or real. Pattern: a RegExp source matched against
   * the URL up to its query string (like qa.stub). Method '*' matches any.
   */
  observe(alias: string, method: string, pathPattern: string): void {
    const re = new RegExp(\`\${pathPattern}(\\\\?.*)?$\`);
    const wanted = method.toUpperCase();
    this.page.on('request', (request) => {
      if ((wanted === '*' || request.method() === wanted) && re.test(request.url())) this.record(alias, request);
    });
  }

  /** The last observed request for an alias; its URL carries the query parameters. */
  lastRequest(alias: string): QaCall | undefined {
    const calls = this.callsFor(alias);
    return calls[calls.length - 1];
  }

  /** The request happened (at least min times). Returns the last one. */
  async expectRequestMade(alias: string, min = 1): Promise<QaCall> {
    await expect.poll(() => this.callsFor(alias).length, { message: \`expected a request aliased "\${alias}" to be sent\` }).toBeGreaterThanOrEqual(min);
    return this.lastRequest(alias)!;
  }

  /**
   * The request did not happen: checked once the page's network has gone
   * quiet, so a late request is still caught. Works against a real backend.
   */
  async expectRequestNotMade(alias: string): Promise<void> {
    await this.settle();
    expect(this.callsFor(alias), \`expected no request aliased "\${alias}" to be sent\`).toHaveLength(0);
  }

  /** Exactly n matching requests, counted once the network is quiet. */
  async expectRequestCount(alias: string, count: number): Promise<void> {
    await this.settle();
    expect(this.callsFor(alias), \`expected \${count} request(s) aliased "\${alias}"\`).toHaveLength(count);
  }

  /** Waits for a response whose URL matches the pattern (and status, when given). */
  async waitForRelevantResponse(pathPattern: string, status?: number): Promise<{ status: number; url: string }> {
    const re = new RegExp(\`\${pathPattern}(\\\\?.*)?$\`);
    const res = await this.page.waitForResponse((r) => re.test(r.url()) && (status === undefined || r.status() === status));
    return { status: res.status(), url: res.url() };
  }

  /**
   * A deterministic response for ONE endpoint, active whether or not the rest
   * of the API is stubbed: controls the data a condition depends on (a user
   * without user_email), simulates a failure, or keeps a write from reaching
   * shared data. Everything else still talks to the real backend.
   */
  async intercept(method: string, pathPattern: string, response: { statusCode?: number; body?: unknown }, alias?: string): Promise<void> {
    const re = new RegExp(\`\${pathPattern}(\\\\?.*)?$\`);
    const wanted = method.toUpperCase();
    this.intercepted.push({ method: wanted, re });
    await this.page.route(re, async (route, request) => {
      if (request.method() !== wanted || request.resourceType() === 'document') return route.fallback();
      if (alias) this.record(alias, request);
      await route.fulfill({ status: response.statusCode ?? 200, contentType: 'application/json', body: JSON.stringify(response.body ?? {}) });
    });
  }

  /* -- Flows (pages/*.flows.ts): user journeys traced from the source ------ */

  /** One table / data-grid row (0-based, header excluded), or one column's cell in it. */
  row(index: number, column?: string | null): Locator {
    // By the grid's own row index: a row with pinned columns is rendered as several row elements
    // (the pinned "Actions" part is separate), and all of them carry the same data-rowindex.
    const rows = this.page.locator('[role="row"][data-rowindex="' + index + '"]')
      .or(this.page.locator('table tbody tr:nth-child(' + (index + 1) + ')'));
    return column ? rows.locator('[data-field="' + column + '"]') : rows.first();
  }

  /**
   * Runs a journey: each step clicks the first locator candidate that finds
   * exactly one visible element (in a row, the row's own), a form is completed
   * before its submit, and a row whose data leads down another code branch (the
   * next step never appears) is left for the next row. Every request that
   * writes data is answered here, never by the real backend: the journey's own
   * (under their aliases, 200 unless opts.respond says otherwise) and any other.
   */
  async runFlow(spec: FlowSpec, opts: FlowOptions = {}): Promise<void> {
    await this.blockWrites();
    for (const g of spec.guards) {
      if (this.intercepted.some((i) => i.method === g.method.toUpperCase() && i.re.test(g.path))) continue; // the test answers it
      await this.intercept(g.method, g.path, opts.respond?.[g.alias] ?? { statusCode: 200, body: {} }, g.alias);
    }
    const here = () => normalizePath(new URL(this.page.url(), 'http://x').pathname);
    if (spec.route && opts.goto !== false && here() !== normalizePath(spec.route)) {
      if (spec.entry) {
        await this.page.goto(spec.entry.via);
        const link = this.page.locator('a[href^="' + spec.entry.link + '"]').first();
        await link.waitFor({ state: 'attached', timeout: 20000 }).catch(() => {
          throw new Error('Flow ' + spec.name + ': no link to ' + spec.entry!.link + ' on ' + spec.entry!.via + ' to open it with real data');
        });
        await this.page.goto((await link.getAttribute('href'))!);
      } else {
        await this.page.goto(spec.route);
      }
    }
    const perRow = spec.steps.some((st) => st.row);
    // Looking through rows for one whose data takes the journey's branch takes time: give the test room for it.
    if (perRow) { try { base.info().setTimeout(base.info().timeout + 150000); } catch { /* outside a test */ } }
    let row = opts.row ?? 0;
    let last = '';
    for (let attempt = 0; attempt < (perRow ? 12 : 1); attempt++, row++) {
      const failure = await this.tryFlow(spec, row, opts);
      if (!failure) return;
      last = failure.message;
      if (!perRow || !failure.branch) break;
      await this.closeDialogs();
    }
    throw new Error('Flow ' + spec.name + ' did not complete: ' + last);
  }

  /**
   * The request was sent after the last flow's final step (the save, the
   * confirmation) - not by the steps before it. A flow may try several table
   * rows; requests from the rows it abandoned or from opening a dialog do not count.
   */
  async expectRequestMadeAfterFlow(alias: string): Promise<void> {
    await expect.poll(() => this.callsFor(alias).filter((c) => c.at >= this.finalStepAt).length, {
      message: 'expected a request aliased "' + alias + '" after the flow\\'s final step',
    }).toBeGreaterThanOrEqual(1);
  }

  /** No such request after the last flow's final step, once the network is quiet. */
  async expectRequestNotMadeAfterFlow(alias: string): Promise<void> {
    await this.settle();
    expect(this.callsFor(alias).filter((c) => c.at >= this.finalStepAt), 'expected no request aliased "' + alias + '" after the flow\\'s final step').toHaveLength(0);
  }

  private async tryFlow(spec: FlowSpec, row: number, opts: FlowOptions): Promise<{ message: string; branch: boolean } | null> {
    for (let i = 0; i < spec.steps.length; i++) {
      const step = spec.steps[i]!;
      if (step.action === 'submit' || step.fields.length) await this.completeForm(step.fields, opts.values ?? {}, row);
      let target: Locator;
      try {
        target = await this.pick(step.candidates, row, step.what, i === 0 ? 15000 : 8000);
      } catch (e) {
        return { message: 'step ' + (i + 1) + ' (' + step.what + '): ' + (e as Error).message, branch: i > 0 };
      }
      if (i === spec.steps.length - 1) this.finalStepAt = Date.now();
      await target.click();
      const next = spec.steps[i + 1];
      if (next && !(await this.pick(next.candidates, row, next.what, 6000).then(() => true, () => false))) {
        return { message: 'after step ' + (i + 1) + ' (' + step.what + ') the next step never appeared: ' + next.what + ' (row ' + row + ')', branch: true };
      }
    }
    return null;
  }

  private flowLocator(l: FlowLocator, row: number): Locator {
    const base: Page | Locator = l.row ? this.row(row, l.row.column) : l.inDialog ? this.page.getByRole('dialog').last() : this.page;
    if (l.role) return base.getByRole(l.role as Parameters<Page['getByRole']>[0], l.name ? { name: l.name, exact: true } : {});
    if (l.label) return base.getByLabel(l.label, { exact: true });
    if (l.text) return base.getByText(l.text, { exact: true });
    return base.locator(l.css ?? '');
  }

  /** The first candidate that finds exactly one visible element (in a row: its first), polling until the timeout. */
  private async pick(candidates: FlowLocator[], row: number, what: string, timeoutMs: number): Promise<Locator> {
    const deadline = Date.now() + timeoutMs;
    for (;;) {
      const tried: string[] = [];
      for (const c of candidates) {
        const loc = this.flowLocator(c, row);
        let n = await loc.count().catch(() => 0);
        // A data grid renders only the columns in view: bring the column's header into view, and its cells follow.
        if (n === 0 && c.row?.column) {
          await this.page.locator('[role="columnheader"][data-field="' + c.row.column + '"]').first().scrollIntoViewIfNeeded({ timeout: 2000 }).catch(() => undefined);
          await this.row(row).scrollIntoViewIfNeeded({ timeout: 2000 }).catch(() => undefined);
          n = await loc.count().catch(() => 0);
        }
        const visible = n > 0 && await loc.first().isVisible().catch(() => false);
        tried.push(JSON.stringify(c) + ' -> ' + n + (visible ? ' visible' : ''));
        if (visible && (n === 1 || c.row)) return loc.first();
      }
      if (Date.now() > deadline) throw new Error('could not find ' + what + '; tried ' + tried.join(', '));
      await new Promise((r) => setTimeout(r, 250));
    }
  }

  /** Fills the fields the journey names, then whatever else the open dialog requires and is still empty. */
  private async completeForm(fields: FlowSpec['steps'][number]['fields'], values: Record<string, string>, row: number): Promise<void> {
    for (const f of fields) {
      const input = await this.pick(f.candidates, row, 'field "' + f.what + '"', 5000).catch(() => null);
      if (!input) continue;
      const value = values[f.what] ?? (f.date ? await this.dateFor(input) : 'QA test');
      await input.click();
      await input.fill(value).catch(() => undefined);
      // A sectioned date field (MUI X) ignores fill: type the digits.
      if ((await input.inputValue().catch(() => '')).replace(/\\D/g, '') === '') await input.pressSequentially(value.replace(/\\D/g, ''));
    }
    const dialog = this.page.getByRole('dialog').last();
    const groups = dialog.locator('[role="radiogroup"]');
    for (let i = 0; i < await groups.count(); i++) {
      const g = groups.nth(i);
      if (await g.locator('input[type="radio"]:checked').count() === 0) await g.getByRole('radio').first().check().catch(() => undefined);
    }
    const required = dialog.locator('input[required]:not([type="hidden"]):not([disabled]):not([type="radio"]):not([type="checkbox"]), textarea[required]:not([disabled]), input[aria-required="true"]:not([disabled])');
    for (let i = 0; i < await required.count(); i++) {
      const el = required.nth(i);
      if (await el.isVisible().catch(() => false) && (await el.inputValue().catch(() => 'x')) === '') await el.fill('QA test').catch(() => undefined);
    }
  }

  /** Today, written the way the field's placeholder asks (YYYY-MM-DD, MM/DD/YYYY, DD.MM.YYYY ...). */
  private async dateFor(input: Locator): Promise<string> {
    const d = new Date();
    const pad = (n: number) => String(n).padStart(2, '0');
    const format = (await input.getAttribute('placeholder').catch(() => null)) ?? 'YYYY-MM-DD';
    return format.replace(/YYYY/i, String(d.getFullYear())).replace(/MM/, pad(d.getMonth() + 1)).replace(/DD/i, pad(d.getDate()));
  }

  private async closeDialogs(): Promise<void> {
    for (let i = 0; i < 3 && await this.page.getByRole('dialog').count() > 0; i++) {
      await this.page.keyboard.press('Escape');
      await this.page.getByRole('dialog').last().waitFor({ state: 'hidden', timeout: 2000 }).catch(() => undefined);
    }
  }

  /** From now on, a request that writes data and that no test or flow answers is answered with 200 {} (recorded as "blocked"). */
  private async blockWrites(): Promise<void> {
    if (this.writesBlocked) return;
    this.writesBlocked = true;
    await this.page.route(() => true, async (route, request) => {
      const method = request.method();
      if (['GET', 'HEAD', 'OPTIONS'].includes(method) || !['xhr', 'fetch'].includes(request.resourceType())) return route.fallback();
      const path = new URL(request.url()).pathname;
      if (/auth|login|logout|token|refresh|session/i.test(path)) return route.fallback();
      if (this.intercepted.some((i) => i.method === method && i.re.test(path))) return route.fallback();
      this.record('blocked', request);
      await route.fulfill({ status: 200, contentType: 'application/json', body: '{}' });
    });
  }

  async expectPath(route: string): Promise<void> {
    await expect.poll(() => normalizePath(new URL(this.page.url()).pathname), { message: \`expected the page to be at \${route}\` })
      .toBe(normalizePath(route));
  }

  /** The form refused the value: native validity, aria-invalid, or a visible error. */
  async expectRejected(fieldSelector: string): Promise<void> {
    const field = this.page.locator(fieldSelector).first();
    await expect.poll(() => field.evaluate((input, selectors) => {
      const el = input as HTMLInputElement;
      const nativeInvalid = typeof el.checkValidity === 'function' && !el.checkValidity();
      const visible = (e: Element) => { const h = e as HTMLElement; return !!(h.offsetWidth || h.offsetHeight || h.getClientRects().length); };
      const shownError = Array.from(el.ownerDocument.querySelectorAll(selectors)).some(visible);
      return nativeInvalid || shownError;
    }, ERROR_SELECTORS), { message: \`expected the application to reject the value in \${fieldSelector}\` }).toBe(true);
  }

  async expectAccepted(fieldSelector: string): Promise<void> {
    const field = this.page.locator(fieldSelector).first();
    await expect.poll(() => field.evaluate((input) => {
      const el = input as HTMLInputElement;
      const nativeValid = typeof el.checkValidity !== 'function' || el.checkValidity();
      return nativeValid && el.getAttribute('aria-invalid') !== 'true';
    }), { message: \`expected \${fieldSelector} to accept the value\` }).toBe(true);
  }

  /**
   * Either the input itself caps the length (maxlength), or submitting the
   * over-long value is rejected. Both are valid enforcement of the limit.
   */
  async expectMaxEnforced(fieldSelector: string, max: number, submitSelector: string): Promise<void> {
    const text = await this.page.locator(fieldSelector).first().inputValue();
    const numeric = Number(text);
    if (Number.isNaN(numeric) && text.length <= max) {
      expect(text.length, \`expected the input to cap \${fieldSelector} at \${max} characters\`).toBeLessThanOrEqual(max);
      return;
    }
    await this.page.locator(submitSelector).first().click();
    await this.expectRejected(fieldSelector);
  }

  /** Redirected away, shown a sign-in / forbidden state, and the protected content is absent. */
  async expectAccessDenied(route: string, protectedSelector?: string): Promise<void> {
    await expect.poll(() => this.probe(({ route, selectors, pattern }) => {
      const re = new RegExp(pattern, 'i');
      const path = document.location.pathname.replace(/\\/$/, '') || '/';
      const redirected = path !== (route.replace(/\\/$/, '') || '/');
      const visible = (e: Element) => { const h = e as HTMLElement; return !!(h.offsetWidth || h.offsetHeight || h.getClientRects().length); };
      const deniedElement = Array.from(document.querySelectorAll(selectors)).some((el) => visible(el) && re.test(el.textContent ?? ''));
      return redirected || deniedElement || re.test(document.body?.innerText ?? '');
    }, { route, selectors: DENIED_SELECTORS, pattern: DENIED_TEXT }, false), { message: 'expected access to be denied' }).toBe(true);
    if (protectedSelector) await expect(this.page.locator(protectedSelector)).toHaveCount(0);
  }

  /**
   * Error feedback is visible: an alert, an error toast, or a toast / snackbar /
   * status message whose text reads as an error. Error words elsewhere on the
   * page (a "Failed" status column, a filter) do not count - they are there
   * whether or not anything went wrong.
   */
  async expectErrorShown(): Promise<void> {
    await expect.poll(() => this.probe(({ pattern, errorSelectors, feedbackSelectors }) => {
      const visible = (e: Element) => { const h = e as HTMLElement; return !!(h.offsetWidth || h.offsetHeight || h.getClientRects().length); };
      const text = (e: Element) => (e.textContent ?? '').trim();
      const re = new RegExp(pattern, 'i');
      const errors = Array.from(document.querySelectorAll(errorSelectors)).some((e) => visible(e) && text(e) !== '');
      const feedback = Array.from(document.querySelectorAll(feedbackSelectors)).some((e) => visible(e) && re.test(text(e)));
      return errors || feedback;
    }, { pattern: ERROR_TEXT, errorSelectors: ERROR_FEEDBACK_SELECTORS, feedbackSelectors: FEEDBACK_SELECTORS }, false), { message: 'expected an error alert or toast to be shown to the user' }).toBe(true);
  }

  /**
   * No visible, non-empty alert in the page's own DOM. Deliberately not a CSS
   * locator: Playwright's CSS pierces shadow roots, where frameworks keep
   * hidden live regions (Next.js's route announcer has role="alert").
   */
  async expectNoAlert(): Promise<void> {
    await expect.poll(() => this.probe(() => {
      const visible = (e: Element) => { const h = e as HTMLElement; return !!(h.offsetWidth || h.offsetHeight || h.getClientRects().length); };
      return Array.from(document.querySelectorAll('[role="alert"]'))
        .filter((el) => visible(el) && (el.textContent ?? '').trim() !== '')
        .map((el) => (el.textContent ?? '').trim().slice(0, 120));
    }, undefined, ['(page is navigating)']), { message: 'expected no error alert to be shown' }).toEqual([]);
  }

  async expectEmptyState(): Promise<void> {
    await expect.poll(() => this.probe((pattern) => {
      const visible = (e: Element) => { const h = e as HTMLElement; return !!(h.offsetWidth || h.offsetHeight || h.getClientRects().length); };
      const marked = Array.from(document.querySelectorAll('[data-testid*="empty"]')).some(visible);
      return marked || new RegExp(pattern, 'i').test(document.body?.innerText ?? '');
    }, EMPTY_TEXT, false), { message: 'expected an empty state to be shown' }).toBe(true);
  }
}

/**
 * Evidence capture (spec sections 16 and 19). Playwright records video,
 * screenshots and traces itself; console output, network activity and the DOM
 * at the point of failure are collected here and attached to the test result.
 * Collecting evidence must never be able to fail the test it is observing.
 */
/**
 * A first-run welcome or product-tour dialog can cover any page, and a modal
 * hides everything behind it. Playwright closes it whenever it appears, before
 * the next action or assertion - the way a person would. Only a dialog that is
 * plainly an onboarding tour is matched; dialogs under test are left alone.
 * QA_DISMISS_ONBOARDING=0 turns this off.
 */
async function handleOnboarding(page: Page): Promise<void> {
  if (process.env.QA_DISMISS_ONBOARDING === '0') return;
  const tour = page.locator('[role="dialog"], [aria-modal="true"], .MuiDialog-root, .modal.show')
    .filter({ hasText: /welcome|take a tour|product tour|let'?s get started|what'?s new|onboarding/i }).first();
  await page.addLocatorHandler(tour, async (overlay) => {
    const close = overlay.locator('button[aria-label*="close" i], button[aria-label*="dismiss" i], button:has(svg[data-testid*="Close"]), button:has-text("Skip"), button:has-text("Close"), button:has-text("Got it"), button:has-text("×")').first();
    if (await close.isVisible().catch(() => false)) await close.click();
    else await page.keyboard.press('Escape');
  });
}

export const test = base.extend<{ qa: Qa; qaEvidence: void }>({
  qaEvidence: [async ({ page }, use, testInfo) => {
    await handleOnboarding(page);
    const consoleLogs: string[] = [];
    const network: string[] = [];
    const started = new WeakMap<Request, number>();
    const push = (list: string[], line: string) => { if (list.length < 300) list.push(line); };

    page.on('console', (msg) => push(consoleLogs, \`[\${msg.type()}] \${msg.text()}\`));
    // An uncaught application error is evidence, not a reason to abort the run.
    page.on('pageerror', (err) => push(consoleLogs, \`[uncaught] \${err.message}\`));
    page.on('request', (req) => started.set(req, Date.now()));
    page.on('requestfinished', (req) => {
      void req.response().then((res) => {
        push(network, \`\${req.method()} \${req.url()} -> \${res?.status() ?? '?'} (\${Date.now() - (started.get(req) ?? Date.now())}ms)\`);
      }).catch(() => {});
    });
    page.on('requestfailed', (req) => push(network, \`\${req.method()} \${req.url()} -> FAILED \${req.failure()?.errorText ?? ''}\`));

    await use();

    const evidence: Record<string, unknown> = { console: consoleLogs, network };
    if (testInfo.status !== testInfo.expectedStatus) {
      try {
        const html = await page.content();
        evidence['dom'] = [html.length > 200000 ? \`\${html.slice(0, 200000)}\\n<!-- truncated -->\` : html];
        evidence['url'] = [page.url()];
      } catch { /* the page may already be gone */ }
    }
    try {
      await testInfo.attach('qa-evidence', { body: JSON.stringify(evidence), contentType: 'application/json' });
    } catch { /* non-fatal */ }
  }, { auto: true }],

  qa: async ({ page }, use) => {
    await use(new Qa(page));
  },
});

export { expect };
`;

const PROGRESS_REPORTER = `import fs from 'node:fs';

/**
 * Appends one JSON line per event to QA_PROGRESS_FILE. Playwright writes its
 * JSON report only when the run ends; if the run is cut short (a timeout, a
 * stop), these lines are what the review recovers its results from, and the
 * last "testBegin" says which test was running.
 */
interface Attachment { name: string; contentType: string; path?: string; body?: Buffer }
interface Result { retry: number; status: string; duration: number; error?: { message?: string; stack?: string }; attachments: Attachment[] }
interface TestCase { title: string; titlePath(): string[]; location: { file: string }; annotations: unknown[]; outcome(): string }
interface Suite { allTests(): unknown[] }

export default class ProgressReporter {
  private readonly file = process.env.QA_PROGRESS_FILE ?? '';

  private write(event: Record<string, unknown>): void {
    if (!this.file) return;
    try { fs.appendFileSync(this.file, JSON.stringify(event) + '\\n'); } catch { /* evidence must not fail the run */ }
  }

  onBegin(_config: unknown, suite: Suite): void {
    this.write({ type: 'begin', total: suite.allTests().length });
  }

  onTestBegin(test: TestCase, result: Result): void {
    this.write({ type: 'testBegin', title: test.title, titlePath: test.titlePath().slice(3), file: test.location.file, retry: result.retry });
  }

  onTestEnd(test: TestCase, result: Result): void {
    this.write({
      type: 'testEnd', title: test.title, titlePath: test.titlePath().slice(3), file: test.location.file,
      retry: result.retry, status: result.status, outcome: test.outcome(), duration: result.duration,
      error: result.error ? { message: result.error.message, stack: result.error.stack } : undefined,
      annotations: test.annotations,
      attachments: result.attachments.map((a) => ({
        name: a.name, contentType: a.contentType, path: a.path,
        body: a.body && a.body.length < 300000 ? a.body.toString('base64') : undefined,
      })),
    });
  }

  onEnd(result: { status: string }): void {
    this.write({ type: 'end', status: result.status });
  }

  printsToStdio(): boolean {
    return false;
  }
}
`;

/**
 * The qa fixture's methods and properties, read from its source so preflight
 * validation (playwright/preflight.ts) can never disagree with what exists.
 */
export const QA_HELPERS: string[] = (() => {
  const body = SUPPORT_QA.slice(SUPPORT_QA.indexOf('export class Qa'), SUPPORT_QA.indexOf('\nexport const test'));
  // Private members are the fixture's own machinery, not helpers a test may call.
  const names = [...body.matchAll(/^ {2}(private )?(?:readonly |async )*(\w+)\s*[(:<]/gm)].filter((m) => !m[1]).map((m) => m[2]!);
  return [...new Set(names)].filter((n) => n !== 'constructor' && !/^(record|probe|calls|if|for|while|return|switch|const|let|await)$/.test(n));
})();

const TSCONFIG = `{
  "compilerOptions": {
    "target": "ES2022",
    "lib": ["ES2022", "DOM"],
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "types": ["node"],
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "resolveJsonModule": true,
    "noEmit": true
  },
  "include": ["tests/**/*.ts", "pages/**/*.ts", "support/**/*.ts", "utils/**/*.ts", "playwright.config.ts"]
}
`;

const UTILS_DATA = `/**
 * Deterministic test data helpers.
 *
 * Tests use these instead of literal values so a rerun does not collide with
 * data created by a previous run.
 */
export function uniqueSuffix(): string {
  return \`\${Date.now().toString(36)}\${Math.random().toString(36).slice(2, 6)}\`;
}

export function uniqueEmail(prefix = 'qa'): string {
  return \`\${prefix}+\${uniqueSuffix()}@example.test\`;
}

export function stringOfLength(length: number, filler = 'a'): string {
  return filler.repeat(Math.max(0, length));
}

/** A value one step past a numeric boundary, for boundary scenarios. */
export function justOver(limit: number): number { return limit + 1; }
export function justUnder(limit: number): number { return limit - 1; }
`;

/**
 * Makes "playwright" importable from the suite even when the workspace root
 * lives outside this repository's node_modules tree. The link points at the
 * same package the runner launches, so config, fixture and CLI share one copy.
 */
function linkPlaywright(root: string): void {
  const require = createRequire(import.meta.url);
  for (const name of ['playwright', 'playwright-core']) {
    let pkgDir: string;
    try { pkgDir = path.dirname(require.resolve(`${name}/package.json`)); } catch { continue; }
    const link = path.join(root, 'node_modules', name);
    try {
      if (fs.existsSync(link)) continue;
      fs.mkdirSync(path.dirname(link), { recursive: true });
      fs.symlinkSync(pkgDir, link, process.platform === 'win32' ? 'junction' : 'dir');
    } catch (e) {
      log.warn(`Could not link ${name} into the suite: ${(e as Error).message}`);
    }
  }
}

/**
 * Creates (or refreshes) the suite skeleton. Spec files and page objects are
 * written separately by codegen so regeneration never clobbers the skeleton.
 */
export function ensureSuiteScaffold(projectId: string): SuiteLayout {
  const layout = suiteLayout(projectId);

  for (const dir of [
    layout.root, layout.testsDir, layout.pagesDir, layout.fixturesDir,
    layout.supportDir, layout.utilsDir, layout.artifactsDir, layout.runsDir, layout.screenshotsDir,
  ]) {
    fs.mkdirSync(dir, { recursive: true });
  }

  writeIfChanged(path.join(layout.root, 'playwright.config.ts'), PLAYWRIGHT_CONFIG);
  writeIfChanged(path.join(layout.root, 'tsconfig.json'), TSCONFIG);
  writeIfChanged(path.join(layout.supportDir, 'qa.ts'), SUPPORT_QA);
  writeIfChanged(path.join(layout.supportDir, 'progress-reporter.ts'), PROGRESS_REPORTER);
  writeIfChanged(path.join(layout.utilsDir, 'data.ts'), UTILS_DATA);
  linkPlaywright(layout.root);

  log.debug(`Suite scaffold ready at ${layout.root}`);
  return layout;
}

function writeIfChanged(file: string, content: string): void {
  try {
    if (fs.existsSync(file) && fs.readFileSync(file, 'utf8') === content) return;
  } catch { /* fall through and write */ }
  fs.writeFileSync(file, content, 'utf8');
}

export { writeIfChanged };
